name: crm_backend

services:
  db:
    image: postgres:15-alpine
    container_name: crm_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kamboj@2004
      POSTGRES_DB: CRM_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d CRM_DATABASE" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: crm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: crm_backend_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Kamboj%402004@db:5432/CRM_DATABASE
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - ACCESS_TOKEN_SECRET=4e2cfc23e8009dfd7a2fa71da05c48b29ecb7194685ffbcfcebf43cb4620f30c
      - REFRESH_TOKEN_SECRET=fb97ea63c4cbb80dc2463fbda7e4ba3e472288339b1399882a89c89ee4a47854
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Deploy migrations, run seeds, and start the app automatically
    # command: sh -c "npx prisma migrate deploy && npm run seed && npm start"

volumes:
  postgres_data:
  redis_data:
